
 # this worker will also run zmap

services:
  # monitoring
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
      - '--web.listen-address=:9090'
    # listens by default on 9100 --> host mode
    # ports:
    #   - 9100:9100
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    network_mode: host
    command:
      - '-port=9080'
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  ## producer
  ddr-ipv6-producer:
    image: ghcr.io/steffsas/doe-hunter:latest
    container_name: ddr-ipv6-producer
    restart: always
    environment:
      - RUN=producer
      - IP_VERSION=ipv6
      - PROTOCOL=ddr
      - THREADS=1
      - PRODUCER_WATCH_DIRECTORY=/data/ipv6
      # this is the default blocklist
      - BLOCKLIST_FILE_PATH=blocklist.conf
      - KAFKA_SERVER=${KAFKA_SERVER}
      - MONGO_SERVER=${MONGO_SERVER}
      - VANTAGE_POINT=hpi
      - LOG_LEVEL=DEBUG
    volumes:
      - /data/ipv6/:/data/ipv6/
    depends_on:
      - hitlist-downloader
    # needed to access db-1
    network_mode: host

  ddr-ipv4-producer:
    image: ghcr.io/steffsas/doe-hunter:latest
    container_name: ddr-ipv4-producer
    restart: always
    environment:
      - RUN=producer
      - IP_VERSION=ipv4
      - PROTOCOL=ddr
      - THREADS=1
      - PRODUCER_WATCH_DIRECTORY=/data/ipv4
      # this is the default blocklist
      - BLOCKLIST_FILE_PATH=blocklist.conf
      - KAFKA_SERVER=${KAFKA_SERVER}
      - MONGO_SERVER=${MONGO_SERVER}
      - VANTAGE_POINT=hpi
      - LOG_LEVEL=DEBUG
    volumes:
      - /data/ipv4/:/data/ipv4/
    # needed to access db-1
    network_mode: host

  # to download latest ipv6 scans form ipv6 hitlist
  hitlist-downloader:
    image: ghcr.io/steffsas/hitlist-downloader:latest
    container_name: hitlist-downloader
    restart: always
    environment:
      - URL=${IPV6_HITLIST_URL}
      - DOWNLOAD_FOLDER=/data/hitlist/downloads/
      - OUTPUT_FOLDER=/data/output/
      - LOG_FOLDER=/data/hitlist/logs/
      - SCHEDULE=true
      - SCHEDULE_DAILY_AT=00:15:00
    volumes:
      - /data/hitlist/downloads/:/data/hitlist/downloads/
      - /data/hitlist/logs/:/data/hitlist/logs/
      - /data/ipv6/:/data/output/