services:
  ## scanner/consumer
  ddr-scanner:
    image: ghcr.io/steffsas/doe-hunter:latest
    container_name: ddr-scanner
    restart: always
    environment:
      - RUN=consumer
      - PROTOCOL=ddr
      - THREADS=5000
      - KAFKA_SERVER=${KAFKA_SERVER}
      - MONGO_SERVER=${MONGO_SERVER}
      - VANTAGE_POINT=hpi
      - LOG_LEVEL=DEBUG
    # needed to access db-1
    network_mode: host

  doh-scanner:
    image: ghcr.io/steffsas/doe-hunter:latest
    container_name: doh-scanner
    restart: always
    environment:
      - RUN=consumer
      - PROTOCOL=doh
      - THREADS=50
      - KAFKA_SERVER=${KAFKA_SERVER}
      - MONGO_SERVER=${MONGO_SERVER}
      - VANTAGE_POINT=hpi
      - LOG_LEVEL=DEBUG
    # needed to access db-1
    network_mode: host

  dot-scanner:
    image: ghcr.io/steffsas/doe-hunter:latest
    container_name: dot-scanner
    restart: always
    environment:
      - RUN=consumer
      - PROTOCOL=dot
      - THREADS=50
      - KAFKA_SERVER=${KAFKA_SERVER}
      - MONGO_SERVER=${MONGO_SERVER}
      - VANTAGE_POINT=hpi
      - LOG_LEVEL=DEBUG
    # needed to access db-1
    network_mode: host

  doq-scanner:
    image: ghcr.io/steffsas/doe-hunter:latest
    container_name: doq-scanner
    restart: always
    environment:
      - RUN=consumer
      - PROTOCOL=doq
      - THREADS=10
      - KAFKA_SERVER=${KAFKA_SERVER}
      - MONGO_SERVER=${MONGO_SERVER}
      - VANTAGE_POINT=hpi
      - LOG_LEVEL=DEBUG
    # needed to access db-1
    network_mode: host

  ptr-scanner:
    image: ghcr.io/steffsas/doe-hunter:latest
    container_name: ptr-scanner
    restart: always
    environment:
      - RUN=consumer
      - PROTOCOL=ptr
      - THREADS=100
      - KAFKA_SERVER=${KAFKA_SERVER}
      - MONGO_SERVER=${MONGO_SERVER}
      - VANTAGE_POINT=hpi
      - LOG_LEVEL=DEBUG
    # needed to access db-1
    network_mode: host

  edsr-scanner:
    image: ghcr.io/steffsas/doe-hunter:latest
    container_name: edsr-scanner
    restart: always
    environment:
      - RUN=consumer
      - PROTOCOL=edsr
      - THREADS=100
      - KAFKA_SERVER=${KAFKA_SERVER}
      - MONGO_SERVER=${MONGO_SERVER}
      - VANTAGE_POINT=hpi
      - LOG_LEVEL=DEBUG
    # needed to access db-1
    network_mode: host

  certificate-scanner:
    image: ghcr.io/steffsas/doe-hunter:latest
    container_name: certificate-scanner
    restart: always
    environment:
      - RUN=consumer
      - PROTOCOL=certificate
      - THREADS=50
      - KAFKA_SERVER=${KAFKA_SERVER}
      - MONGO_SERVER=${MONGO_SERVER}
      - VANTAGE_POINT=hpi
      - LOG_LEVEL=DEBUG
    # needed to access db-1
    network_mode: host

  fingerprint-scanner:
    image: ghcr.io/steffsas/doe-hunter:latest
    container_name: fingerprint-scanner
    restart: always
    environment:
      - RUN=consumer
      - PROTOCOL=fingerprint
      - THREADS=1000
      - KAFKA_SERVER=${KAFKA_SERVER}
      - MONGO_SERVER=${MONGO_SERVER}
      - VANTAGE_POINT=hpi
      - LOG_LEVEL=DEBUG
    # needed to access db-1
    network_mode: host

  ddr-dnssec-scanner:
    image: ghcr.io/steffsas/doe-hunter:latest
    container_name: ddr-dnssec-scanner
    restart: always
    environment:
      - RUN=consumer
      - PROTOCOL=ddr-dnssec
      - THREADS=1000
      - KAFKA_SERVER=${KAFKA_SERVER}
      - MONGO_SERVER=${MONGO_SERVER}
      - VANTAGE_POINT=hpi
      - LOG_LEVEL=DEBUG
    # needed to access db-1
    network_mode: host