
 # this worker will also run zmap

services:
  ## producer
  ddr-ipv6-producer:
    image: ghcr.io/steffsas/doe-hunter:latest
    restart: always
    environment:
      - RUN=producer
      - PROTOCOL=ddr
      - THREADS=1
      - PRODUCER_WATCH_DIRECTORY=/data/ipv6
      - KAFKA_SERVER=${KAFKA_SERVER}
      - MONGO_SERVER=${MONGO_SERVER}
      - VANTAGE_POINT=hpi
      - LOG_LEVEL=DEBUG
    volumes:
      - /data/ipv6/:/data/ipv6/
    # needed to access db-1
    network_mode: host

  ddr-ipv4-producer:
    image: ghcr.io/steffsas/doe-hunter:latest
    restart: always
    environment:
      - RUN=producer
      - PROTOCOL=ddr
      - THREADS=1
      - PRODUCER_WATCH_DIRECTORY=/data/ipv4
      - KAFKA_SERVER=${KAFKA_SERVER}
      - MONGO_SERVER=${MONGO_SERVER}
      - VANTAGE_POINT=hpi
      - LOG_LEVEL=DEBUG
    volumes:
      - /data/ipv4/:/data/ipv4/
    # needed to access db-1
    network_mode: host