name: Lint and Test
on:
  pull_request:
    branches:
      - main

jobs:
  # basic linting
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'
      - name: lint lib
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ./lib
        
  test:
    name: test-and-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: generate test coverage
        run: go test ./lib/... -coverprofile=./profile.cov -covermode=atomic